name: Ma Jiabo
title: majiabo | personal website to record life
description: personal website, blog,
tags:
  - blog
  - diary
  - life
  - study
email: majiabo@hust.edu.cn
disqus_username: birkhoff
show_hero: true
